const FETCH_STORE_REQUEST = "FETCH_STORE_REQUEST"
const FETCH_STORE_REQUEST_SUCCESS = "FETCH_STORE_REQUEST_SUCCESS"
const FETCH_STORE_ERROR = "FETCH_STORE_ERROR"
const MENU_CLOSE = "MENU_CLOSE"
const MENU_OPEN = "MENU_OPEN"

module.exports = {
    FETCH_STORE_REQUEST,
    FETCH_STORE_REQUEST_SUCCESS,
    FETCH_STORE_ERROR,
    MENU_CLOSE,
    MENU_OPEN
}
